"""create user and settings

Revision ID: 9bc2a23148bd
Revises: ed822f558063
Create Date: 2026-05-29 13:11:30.769086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9bc2a23148bd'
down_revision: Union[str, Sequence[str], None] = 'ed822f558063'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('app_language', sa.Enum('ENGLISH', 'RUSSIAN', 'CZECH', name='applanguage'), nullable=False),
    sa.Column('theme', sa.Enum('DARK', 'LIGHT', name='theme'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(
        'language',
        sa.Column('user_id', sa.Integer(), nullable=True)
    )
    with op.batch_alter_table('language') as batch_op:
        batch_op.create_foreign_key(
            'fk_language_user_id',
            'user',
            ['user_id'],
            ['id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language') as batch_op:
        batch_op.drop_constraint(
            'fk_language_user_id',
            type_='foreignkey'
        )
    op.drop_column('language', 'user_id')
    op.drop_table('user')
    op.drop_table('settings')
    # ### end Alembic commands ###
