"""add notes, remove language from entries, change language name to language id

Revision ID: ed822f558063
Revises: b2f5ab2f06d5
Create Date: 2026-04-08 18:56:24.971793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ed822f558063'
down_revision: Union[str, Sequence[str], None] = 'b2f5ab2f06d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'notes_group',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('language_id', sa.Integer(), nullable=True),
        sa.Column('position', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['language_id'], ['language.id']),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table(
        'note',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.Column('position', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['group_id'], ['notes_group.id']),
        sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table("dictionary_entry") as batch_op:
        batch_op.drop_column("language_name")

    with op.batch_alter_table("entries_group") as batch_op:
        batch_op.add_column(sa.Column("language_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_entries_group_language_id",
            "language",
            ["language_id"],
            ["id"],
        )
        batch_op.drop_column("language_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("entries_group") as batch_op:
        batch_op.add_column(sa.Column('language_name', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'language', ['language_name'], ['name'])
        batch_op.drop_column('language_id')

    with op.batch_alter_table("dictionary_entry") as batch_op:
        batch_op.add_column(sa.Column('language_name', sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key(None, 'language', ['language_name'], ['name'])

    op.drop_table('note')
    op.drop_table('notes_group')
    # ### end Alembic commands ###
